# Generated by Django 2.1.4 on 2020-05-16 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0002_auto_20200514_1217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'About us', 'verbose_name_plural': 'About us'},
        ),
        migrations.AlterModelOptions(
            name='chef',
            options={'verbose_name': 'Chef', 'verbose_name_plural': 'Chefs'},
        ),
        migrations.AlterModelOptions(
            name='why_choose_us',
            options={'verbose_name': 'Why choose us', 'verbose_name_plural': 'Why choose us'},
        ),
    ]
